version: "3.9"

services:
  server:
    build:
      context: ./server
    container_name: ip-server
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app
      - /app/node_modules
    restart: unless-stopped

  client:
    build:
      context: ./client
    container_name: ip-client
    ports:
      - "4000:4000"
    volumes:
      - ./client:/app
      - /app/node_modules
    restart: unless-stopped
